version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rapidticket_local
    ports:
      - "5455:5432"
    networks:
      - rapidticket-network
    volumes:
      - ./src/main/resources/db/001-schema.sql:/docker-entrypoint-initdb.d/001-schema.sql
      - ./src/main/resources/db/002-data.sql:/docker-entrypoint-initdb.d/002-data.sql

networks:
  rapidticket-network:
    driver: bridge
