version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rapidticket_local
    ports:
      - "5455:5432"
    networks:
      - rapidticket-network
    volumes:
      - ./src/main/resources/db/001-schema.sql:/docker-entrypoint-initdb.d/001-schema.sql
      - ./src/main/resources/db/002-data.sql:/docker-entrypoint-initdb.d/002-data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rapidticket-venues-api:1.0.1
    container_name: rapidticket-venues-api
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/rapidticket_local
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - rapidticket-network

networks:
  rapidticket-network:
    driver: bridge
